
=begin
---------------------------------
filedata=Msf::Util::EXE.to_exe_aspx(generate_payload_exe)
---------------------------------

generate_cmdstager
generate_payload
generate_payload_dll
generate_payload_exe
generate_payload_exe_service
generate_payload_msi
generate_single_payload
generate_uuid

---------------------------------
Msf::Util::EXE.methods:
clear_dynamic_base
encode_stub
exe_sub_method
find_payload_tag
generate_nops
get_file_contents
is_eicar_corrupted?
read_replace_script_template
replace_msi_buffer
set_template_default
string_to_pushes
to_bsd_x64_elf
to_bsd_x86_elf
to_dotnetmem
to_exe_asp
to_exe_aspx
to_exe_elf
to_exe_msi
to_exe_vba
to_exe_vbs
to_executable
to_executable_fmt
to_executable_fmt_formats
to_jar
to_jsp_war
to_linux_armle_elf
to_linux_mipsbe_elf
to_linux_mipsle_elf
to_linux_x64_elf
to_linux_x64_elf_dll
to_linux_x86_elf
to_mem_aspx
to_osx_app
to_osx_arm_macho
to_osx_ppc_macho
to_osx_x64_macho
to_osx_x86_macho
to_powershell_command
to_powershell_hta
to_powershell_vba
to_solaris_x86_elf
to_vba
to_war
to_win32pe
to_win32pe_dll
to_win32pe_exe_sub
to_win32pe_old
to_win32pe_psh
to_win32pe_psh_net
to_win32pe_psh_reflection
to_win32pe_service
to_win32pe_vbs
to_win64pe
to_win64pe_dll
to_win64pe_service
to_win64pe_vbs
to_winpe_only
win32_rwx_exec
win32_rwx_exec_thread

=end
